repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            ^data/python/.*/.*|
            ^nvtransformer/nvtransformer/tools/samples/.*
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            ^data/python/.*/.*|
            ^nvtransformer/nvtransformer/tools/samples/.*
          )
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: |
          (?x)^(
            .*test.*|
            ^CHANGELOG.md$|
          )
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff
        exclude: |
          (?x)^(
            ^data/python/.*/.*|
            ^ray-rapids/cugraph-dev/.*
          )
        files: ray-rapids/cugraph-dev/.*$
        types_or: [ python, pyi ]
        args: [ --fix ]

default_language_version:
    python: python3
exclude: '\.(svg|ts|css)$'
